### PR TITLE
Fixed imports

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by GreyCat** [comment]
Thanks!

**Comment by flucknugget** [comment]
@KOLANICH I have to revert this to make it work on Windows with Python 3.6 and `python setup.py develop`. What's your setup?

**Comment by KOLANICH** [comment]
That's strange. I gonna look into it tomorrow.

>What's your setup?

Windows 7, Anaconda, Python 3.6.1.  But I have not actually tested the package.

BTW, I guess it would be nice to have some test and CI scripts.

**Comment by KOLANICH** [comment]
Works for me (after fixes to support python3). Please check if you use python 3.

**Comment by flucknugget** [comment]
My problem was that I was running it as a script file (`python cli.py`) and it needs to be run as a module (`python -m kaitafs.cli`). I fucked up my fork but I'll redo it and add this info to the readme.

Yes tests would be really nice, I think the most important thing to test is mounting any fs with multiple Python versions on multiple systems. I'd be happy to write some tests if somebody who knows what they're doing (maybe you?) agrees to review them. I don't wanna make my incompetence other peoples problem. I'll make an issue about it.

**Pull request merged**
